// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SEP_DataAPI.Model;

namespace SEP_DataAPI.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20190507092538_SmallCheck")]
    partial class SmallCheck
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SEP_DataAPI.Model.Account", b =>
                {
                    b.Property<string>("Username")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("username")
                        .HasMaxLength(50);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnName("password")
                        .HasMaxLength(50);

                    b.Property<bool>("isAdmin");

                    b.HasKey("Username");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("SEP_DataAPI.Model.DateDim", b =>
                {
                    b.Property<int>("DimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Dim_ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<int>("Month");

                    b.Property<int>("Quarter");

                    b.Property<int>("Week");

                    b.Property<int>("Year");

                    b.HasKey("DimId");

                    b.ToTable("Date_Dim");
                });

            modelBuilder.Entity("SEP_DataAPI.Model.Fact", b =>
                {
                    b.Property<int>("FactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Fact_ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DimId")
                        .HasColumnName("Dim_ID");

                    b.Property<int>("RoomId")
                        .HasColumnName("Room_ID");

                    b.Property<int>("SensorsId")
                        .HasColumnName("Sensors_ID");

                    b.Property<int?>("Timespan");

                    b.HasKey("FactId");

                    b.HasIndex("DimId");

                    b.HasIndex("RoomId");

                    b.HasIndex("SensorsId");

                    b.ToTable("Facts");
                });

            modelBuilder.Entity("SEP_DataAPI.Model.RoomDim", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Room_ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DataCreated")
                        .HasColumnType("datetime");

                    b.Property<string>("Teacher")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("RoomId");

                    b.ToTable("Room_Dim");
                });

            modelBuilder.Entity("SEP_DataAPI.Model.SensorDim", b =>
                {
                    b.Property<int>("SensorsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Sensors_ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal?>("Co2")
                        .HasColumnName("CO2")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<double?>("TempC")
                        .HasColumnName("Temp_c");

                    b.Property<double?>("TempF")
                        .HasColumnName("Temp_f");

                    b.HasKey("SensorsId");

                    b.ToTable("Sensor_Dim");
                });

            modelBuilder.Entity("SEP_DataAPI.Model.Fact", b =>
                {
                    b.HasOne("SEP_DataAPI.Model.DateDim", "Dim")
                        .WithMany("Facts")
                        .HasForeignKey("DimId")
                        .HasConstraintName("FK_Facts_Date_Dim");

                    b.HasOne("SEP_DataAPI.Model.RoomDim", "Room")
                        .WithMany("Facts")
                        .HasForeignKey("RoomId")
                        .HasConstraintName("FK_Facts_Room_Dim");

                    b.HasOne("SEP_DataAPI.Model.SensorDim", "Sensors")
                        .WithMany("Facts")
                        .HasForeignKey("SensorsId")
                        .HasConstraintName("FK_Facts_Sensor_Dim");
                });
#pragma warning restore 612, 618
        }
    }
}
